version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres-container
    ports:
      - "5432:5432"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api-container
    depends_on:
      - db
    ports:
      - "8000:8000"
